config/routes.rb
Rails.application.routes.draw do
  devise_for :inn_owners, controllers: { registrations: 'registrations' }
  root to: 'home#index'

  resources :inns, only: [:new, :create, :show, :edit, :update] do
    post 'inactive', on: :member
    post 'active', on: :member
  end
  
  get 'my_inn', to: 'inns#my_inn'
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :inn
  
  validates :street_name, :number, :neighborhood, :city, :state, :zip_code,
            presence: true

  def formatted_neighborhood_city_state
    "#{self.neighborhood}, #{self.city} - #{self.state}"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/inn.rb
class Inn < ApplicationRecord
  belongs_to :inn_owner

  has_one :address
  accepts_nested_attributes_for :address

  has_one :payment_method
  accepts_nested_attributes_for :payment_method

  enum :status, { active: 2, inactive: 0 }
  
  validates :brand_name, :registration_number, :phone_number, :checkin_time,
            :checkout_time, presence: true

  
end

app/models/inn_owner.rb
class InnOwner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_one :inn
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  belongs_to :inn
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def force_inn_creation_for_owners
    if inn_owner_signed_in? && current_inn_owner.inn.nil?
      return redirect_to new_inn_path, alert: 'É necessário cadastrar uma pousada para continuar.'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :force_inn_creation_for_owners

  def index 
  end
end

app/controllers/inn_owners_controller.rb
class InnOwnersController < ApplicationController
end

app/controllers/inns_controller.rb
class InnsController < ApplicationController
  before_action :authenticate_inn_owner!, only: [:new, :create, :my_inn, 
                                                 :inactive, :active]
  before_action :set_inn, only: [:show, :edit, :update, :inactive, :active]
  before_action :check_inn_owner, only: [:edit, :update, :inactive, :active]

  def new
    @inn = Inn.new
    @address = @inn.build_address
    @payment_method = @inn.build_payment_method 
  end

  def create
    @inn = current_inn_owner.build_inn(inn_params)
    @address = @inn.build_address(address_params)
    @payment_method = @inn.build_payment_method(payment_method_params)

    if @inn.save
      redirect_to @inn, notice: 'Sua Pousada foi registrada com sucesso!'
    else
      flash.now[:notice] = 'Não foi possível concluir o registro da sua pousada.'
      render 'new', status: :unprocessable_entity
    end
  end

  def show; end

  def edit
    @address = @inn.address
    @payment_method = @inn.payment_method
  end

  def update
    @address = @inn.address
    @address.update(address_params)

    @payment_method = @inn.payment_method
    @payment_method.update(payment_method_params) unless payment_method_params.nil?

    if @inn.update(inn_params)
      redirect_to @inn, notice: 'Sua pousada foi atualizada com sucesso.'
    else
      flash.now[:notice] = 'Não foi possível atualizar sua pousada.'
      render 'edit', status: :unprocessable_entity
    end
  end

  def my_inn
    @inn = current_inn_owner.inn
    render 'show'
  end

  def inactive
    @inn.inactive!
    redirect_to @inn
  end

  def active
    @inn.active!
    redirect_to @inn
  end

  private

  def address_params
    params.require(:address).permit(:street_name, :number, :complement, 
                                    :neighborhood, :city, :state, :zip_code)
  end

  def inn_params
    params.require(:inn).permit(:brand_name, :registration_number, :phone_number,
                                :description, :policy, :pet_friendly, 
                                :checkin_time, :checkout_time)
  end

  def payment_method_params
    unless params[:payment_method].nil?
      params.require(:payment_method).permit(:bank_transfer, :credit_card, 
                                            :debit_card, :cash, :deposit)
    end
  end

  def set_inn
    @inn = Inn.find(params[:id])
  end

  def check_inn_owner
    unless @inn.inn_owner == current_inn_owner
      redirect_to root_path, notice: 'Você não possui autorização para essa ação.'
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    :new_inn
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inn_owners/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/inn_owners/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/inns/_errors.html.erb
<% if @inn.errors.any? %>
  <% @inn.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

<% if !@address.nil? && @address.errors.any? %>
  <% @address.errors.full_messages.each do |msg| %>
    <p><%= msg %></p>
  <% end %>
<% end %>

app/views/inns/_form.html.erb
<%= form_with model: @inn do |f| %>
  <section id="inn-data">
    <div id="brand-name">
      <%= f.label :brand_name %>
      <%= f.text_field :brand_name %>
    </div>
    <div id="registration_number">
      <%= f.label :registration_number %>
      <%= f.text_field :registration_number %>
    </div>
    <div id="phone-number">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number %>
    </div>
  </section>
  <br><br>
  <section id="address-data">
    <%= fields_for @address do |address_f| %>
      <div id="street-name">
        <%= address_f.label :street_name %>
        <%= address_f.text_field :street_name %>
      </div>
      <div id="number">
        <%= address_f.label :number %>
        <%= address_f.text_field :number %>
      </div>
      <div id="complement">
        <%= address_f.label :complement %>
        <%= address_f.text_field :complement %>
      </div>
      <div id="neighborhood">
        <%= address_f.label :neighborhood %>
        <%= address_f.text_field :neighborhood %>
      </div>
      <div id="city">
        <%= address_f.label :city %>
        <%= address_f.text_field :city %>
      </div>
      <div id="state">
        <%= address_f.label :state %>
        <%= address_f.text_field :state %>
      </div>
      <div id="zip-code">
        <%= address_f.label :zip_code %>
        <%= address_f.text_field :zip_code %>
      </div>
    <% end %>
  </section>
  <br><br>
  <section id="inn-policies">
    <div id="description">
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>
    <br>
    <div id="pet-friendly">
      <%= f.label :pet_friendly %> <br>
      <%= f.radio_button :pet_friendly, true %>
      <%= f.label :is_pet_friendly %> <br>
      <%= f.radio_button :pet_friendly, false %>
      <%= f.label :not_pet_friendly %>
    </div>
    <br>
    <div id="inn-policy">
      <%= f.label :policy %>
      <%= f.text_area :policy %>
    </div>
    <br>
    <div id="checkin-time">
      <%= f.label :checkin_time %>
      <%= f.time_field :checkin_time %>
    </div>
    <br>
    <div id="checkout-time">
      <%= f.label :checkout_time %>
      <%= f.time_field :checkout_time %>
    </div>
  </section>
  <br><br>
  <section id="payment-methods">
    <%= fields_for :payment_method do |payment_f| %>
      <h2>Meios de pagamento</h2>
      <div id="pix">
        <%= payment_f.label :bank_transfer %> <br>
        <%= payment_f.radio_button :bank_transfer, true %>
        <%= payment_f.label :accepts %> <br>
        <%= payment_f.radio_button :bank_transfer, false %>
        <%= payment_f.label :refuses %>
      </div>
      <br>
      <div id="credit-card">
        <%= payment_f.label :credit_card %> <br>
        <%= payment_f.radio_button :credit_card, true %>
        <%= payment_f.label :accepts %> <br>
        <%= payment_f.radio_button :credit_card, false %>
        <%= payment_f.label :refuses %>
      </div>
      <br>
      <div id="debit-card">
        <%= payment_f.label :debit_card %> <br>
        <%= payment_f.radio_button :debit_card, true %>
        <%= payment_f.label :accepts %> <br>
        <%= payment_f.radio_button :debit_card, false %>
        <%= payment_f.label :refuses %>
      </div>
      <br>
      <div id="cash">
        <%= payment_f.label :cash %> <br>
        <%= payment_f.radio_button :cash, true %>
        <%= payment_f.label :accepts %> <br>
        <%= payment_f.radio_button :cash, false %>
        <%= payment_f.label :refuses %>
      </div>
      <br>
      <div id="deposit">
        <%= payment_f.label :deposit %> <br>
        <%= payment_f.radio_button :deposit, true %>
        <%= payment_f.label :accepts %> <br>
        <%= payment_f.radio_button :deposit, false %>
        <%= payment_f.label :refuses %>
      </div>
    <% end %>
  </section>

  <%= f.submit %>
<% end %>

app/views/inns/edit.html.erb
<h2>Editar Pousada</h2>

<%= render 'errors' %>

<%= render 'form' %>

app/views/inns/new.html.erb
<h1>Cadastrar Pousada</h1>

<%= render 'errors' %>

<%= render 'form' %>

app/views/inns/show.html.erb
<h1><%= @inn.brand_name %></h1>

<% if inn_owner_signed_in? && @inn.inn_owner == current_inn_owner %>
  <h3>Área do Proprietário</h3>
  <section id="owner-options">
    <%= link_to 'Editar Pousada', edit_inn_path(@inn.id) %> <br>
    <div id="inn-status">
      <% if @inn.active? %>
        <p>Pousada Disponível</p> 
        <%= button_to 'Marcar como Indisponível', inactive_inn_path(@inn) %>
      <% else %>
        <p>Pousada Indisponível</p>
        <%= button_to 'Marcar como Disponível', active_inn_path(@inn) %>
      <% end %>
    </div>
  </section>
<% end %>

<section id="inn-information">
  <h3>Sobre <%= @inn.brand_name %></h3>
  <div>
    <%= @inn.description %>
  </div>
  <dl>
    <div>
      <dt>Horário de check-in:</dt>
      <dd><%= @inn.checkin_time.to_fs(:time)%></dd>
    </div>
    <div>
      <dt>Horário de check-out:</dt>
      <dd><%= @inn.checkout_time.to_fs(:time)%></dd>
    </div>
    <div>
      <dt>Telefone para contato:</dt>
      <dd><%= @inn.phone_number %></dd>
    </div>
  </dl>
</section>

<section id="inn-policies">
  <h3>Políticas de <%= @inn.brand_name %></h3>
  <% if (@inn.description.nil? || @inn.description.empty?) && @inn.pet_friendly.nil? && (@inn.policy.nil? || @inn.policy.empty?) %>
    <p>Ainda não foram informadas as políticas desse local.</p>
  <% else %>
    <div>
      <%= @inn.description %>
    </div>
    <dl>
      <% unless @inn.pet_friendly.nil? %>
        <div>
          <dt>Animais de estimação:</dt>
          <% if @inn.pet_friendly? %>
            <dd>Aceita animais de estimação</dd>
          <% else %>
            <dd>Não aceita animais de estimação</dd>
          <% end %>
        </div>
      <% end %>
      <% unless @inn.policy.nil? || @inn.policy.empty? %>
        <div>
          <dt>Informações adicionais:</dt>
          <dd><%= @inn.policy %></dd>
        </div>
      <% end %>
    </dl>
  <% end %>
</section>

<section id="inn-address">
  <h3>Endereço</h3>
  <div>
    <p><%= "#{@inn.address.street_name}, #{@inn.address.number}" %></p>
    <p><%= @inn.address.formatted_neighborhood_city_state %></p>
    <p><%= "CEP: #{@inn.address.zip_code}" %></p>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pousadaria</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="page-title">
      <%= link_to root_path do %>
        <h1>Pousadaria</h1>
      <% end %>
    </div>
    <nav>
      <% if inn_owner_signed_in? %>
        <%= current_inn_owner.email %> | 
        <%= link_to 'Minha Pousada', my_inn_path %> | 
        <%= button_to 'Sair', destroy_inn_owner_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Seja um Pousadeiro', new_inn_owner_registration_path %> |
        <%= link_to 'Entrar', new_inn_owner_session_path %>
      <% end %>
    </nav>

    <div id="flash-msgs">
      <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>